require_relative '../Podfiles/common.rb'

platform :ios, '16.0'

target 'CrashMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrashMe
  commonUI

end
